version: '3'
# Other docker-compose examples in /examples

services:
  minecraft:
    image: itzg/minecraft-server
    ports:
      - "25565:25565"
    volumes:
      - ./data:/data
    environment:
      EULA: "TRUE"
      ENABLE_RCON: "false"
      VERSION: "1.14.4"
      MEMORY: "1G"
      GUI: "false"
      MAX_MEMORY: "1G"
    restart: always

